### ISSUE TITLE
Can pyproximal convolve variable?

### ISSUE THREAD

**Issue by HIROJAPAN** [PyLops/pyproximal#17]
Is it possible to apply two convolution filters to the variable X, compare the elements of the two arrays, and choose the larger value?　And can pyproximal　solve the problem?

**Comment by mrava87** [comment]
Hi @HIROJAPAN,
thanks for your issue. I am not sure I fully understand your problem, you want to apply two different filters and choose the one that gives the larger value? How would you pose this as an inverse problem?

**Comment by HIROJAPAN** [comment]
Thank you for your reply. Yes, I want to  apply two different filters and choose the one that gives the larger value. But after trying various things, it was possible and I solved it.　Thank you very much.
