### ISSUE TITLE
Can pyproximal be deconvblind in Matlab?

### ISSUE THREAD

**Issue by HIROJAPAN** [PyLops/pyproximal#19]
In the blind deconvolution method, I would like to update the point spread funciton after updating the data term with ADMM using  LinearizedADMM.
Does Pyploximal have a function similar to deconvblind that returns psf in Matlab?
https://jp.mathworks.com/help/images/ref/deconvblind.html?lang=en

**Comment by mrava87** [comment]
Hi,
No we do not provide algorithms to perform blind deconvolution but you have all the building blocks to be able to implement it yourself using pylops Convolve2D and pyproximal solvers :)

**Comment by mrava87** [comment]
Hello @HIROJAPAN, given you have not replied for long time I assume you either find a solution or are not interested anymore. Please re-open if you want to keep discussing this.
