### ISSUE TITLE
Let `epsg` in `AcceleratedProximalGradient` be a vector of values

### ISSUE THREAD

**Issue by eurunuela** [PyLops/pyproximal#41]
Now that the `pylops` FISTA works on matrices of data, it makes sense that the regularization parameter can be a vector of values (one per vector of data in the data matrix).

Implementing this feature will require that the proximals work at the matrix level rather than the vector level.

Edit: I actually think Python would already take care of making proximals works with matrices.

**Comment by mrava87** [comment]
Good point :) I’ll check if the current implementation allows it, probably yes

**Comment by mrava87** [comment]
Sorry for taking so long! Seems like it was as easy as allowing tau to be a vector in the check for tau>0. Of course this will not work with any proximal but for the case of L1 it can work. I am not planning to change also `FISTA` in PyLops as by now `AcceleratedProximalGradient` is more powerful in many ways and I recommend using it over `FISTA` in PyLops

**Comment by eurunuela** [comment]
Thank you @mrava87! I believe I can now use pylops for my analyses.
