### ISSUE TITLE
Categorize/structure penalties

### ISSUE THREAD

**Issue by marcusvaltonen** [PyLops/pyproximal#75]
There are now an increasing amount of penalties being merged. Currently on main:

- Box
- Simplex
- Intersection
- AffineSet
- Quadratic
- Euclidean
- EuclideanBall
- L0Ball
- L1
- L1Ball
- L2
- L2Convolve
- L21
- L21_plus_L1
- Nonlinear
- Huber
- Nuclear
- NuclearBall
- Orthogonal
- VStack
- SCAD
- Log
- ETP
- Geman
- QuadraticEnvelopeCard

I think it would be beneficial to categorize/group these penalties. Today we only have this flat structure, but new users could get confused of what penalties can be applied to what problems. There are many ways of structuring these, but as a first step I suggest

- First level: Separate between vector penalties and matrix-only penalties.
- Second level (perhaps not yet): Separate between convex and non-convex penalties

Any thoughts? They should also be sorted in an alphabetical order in the documentation.

**Comment by mrava87** [comment]
Agree. After the new additions I started to feel the same, nice to have lots but things are getting a bit messy on the doc side.
